const $=id=>document.getElementById(id);
const fields=["type","title","message","date","time","place","details","host","contact","rsvp","accent","textColor","font","compact","symbol","subtitle","image","askGuests","askNote","customQuestion"];
const typeNames={birthday:"ANNIVERSAIRE",party:"INVITATION",outing:"SORTIE",dinner:"DÎNER",custom:"INVITATION"};
let data={inviteId:"",type:"birthday",title:"Mon anniversaire",message:"J’aimerais beaucoup que tu sois là pour partager ce moment avec moi !",date:"",time:"14:30",place:"",details:"",host:"Ethan",contact:"",rsvp:true,theme:"midnight",accent:"#756ff5",textColor:"#ffffff",font:"classic",compact:false,symbol:"✦",subtitle:"",image:"",askGuests:false,askNote:false,customQuestion:""};

function read(){fields.forEach(k=>{const el=$(k);if(!el)return;data[k]=el.type==="checkbox"?el.checked:el.value});return data}
function fill(d){data={...data,...d};fields.forEach(k=>{const el=$(k);if(!el)return;if(el.type==="checkbox")el.checked=!!data[k];else el.value=data[k]??""});document.querySelectorAll(".theme").forEach(x=>x.classList.toggle("active",x.dataset.theme===data.theme));render()}
function render(){
 read();
 $("pType").textContent=typeNames[data.type]||"INVITATION";
 $("pTitle").textContent=data.title||"Votre événement";$("pMessage").textContent=data.message||"";
 $("pDate").textContent=data.date?new Date(data.date+"T12:00:00").toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"}):"—";
 $("pTime").textContent=data.time||"—";$("pPlace").textContent=data.place||"—";$("pDetails").textContent=data.details||"";
 $("pHost").textContent=data.host||"";$("pContact").textContent=data.contact||"";
 $("pSubtitle").textContent=data.subtitle||"";$("pSymbol").textContent=(data.symbol||"✦")+"　·　✧　·　"+(data.symbol||"✦");
 $("rsvpBox").style.display=data.rsvp?"block":"none";
 const inv=$("invitation");inv.className="invitation theme-"+data.theme+" font-"+data.font+(data.compact?" compact":"");inv.style.setProperty("--accent",data.accent||"#756ff5");
 inv.style.color=data.textColor||"";
 $("pImage").style.display=data.image?"block":"none";$("pImage").style.backgroundImage=data.image?"url("+JSON.stringify(data.image)+")":"none";
 $("guestCountWrap").style.display=data.askGuests?"block":"none";$("guestNoteWrap").style.display=data.askNote?"block":"none";$("guestCustomWrap").style.display=data.customQuestion?"block":"none";$("guestCustom").placeholder=data.customQuestion||"";
}
fields.forEach(k=>$(k)?.addEventListener("input",render));
document.querySelectorAll(".theme").forEach(b=>b.onclick=()=>{data.theme=b.dataset.theme;document.querySelectorAll(".theme").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("tab-"+b.dataset.tab).classList.add("active")});

function ensureInviteId(){if(!data.inviteId)data.inviteId="inv_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,8);return data.inviteId}
function encoded(){ensureInviteId();return btoa(unescape(encodeURIComponent(JSON.stringify(read())))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
function decode(s){try{let x=s.replaceAll("-","+").replaceAll("_","/");x+="=".repeat((4-x.length%4)%4);return JSON.parse(decodeURIComponent(escape(atob(x))))}catch{return null}}
function makeUrl(){let u=new URL(location.href);u.search="";u.hash="invite="+encoded();return u.href}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
$("shareBtn").onclick=async()=>{read();let u=makeUrl();$("shareUrl").value=u;try{await navigator.clipboard.writeText(u);toast("Lien créé et copié")}catch{toast("Lien créé")}};
$("shareTop").onclick=()=>{read();$("shareUrl").value=makeUrl();$("shareUrl").scrollIntoView({behavior:"smooth",block:"center"});toast("Lien prêt à partager")};
$("copyBtn").onclick=async()=>{if(!$("shareUrl").value)$("shareUrl").value=makeUrl();try{await navigator.clipboard.writeText($("shareUrl").value);toast("Lien copié")}catch{toast("Sélectionne le lien pour le copier")}};
$("openBtn").onclick=()=>{read();window.open(makeUrl(),"_blank")};
$("saveBtn").onclick=()=>{read();ensureInviteId();let list=JSON.parse(localStorage.getItem("invitations")||"[]");const copy={...data,id:data.id||Date.now()};const index=list.findIndex(x=>x.inviteId===copy.inviteId);if(index>=0)list[index]=copy;else list.unshift(copy);localStorage.setItem("invitations",JSON.stringify(list.slice(0,50)));data=copy;toast(index>=0?"Invitation mise à jour":"Invitation enregistrée")};
$("resetBtn").onclick=()=>fill({inviteId:"",type:"birthday",title:"Mon anniversaire",message:"J’aimerais beaucoup que tu sois là pour partager ce moment avec moi !",date:"",time:"14:30",place:"",details:"",host:"Ethan",contact:"",rsvp:true,theme:"midnight",accent:"#756ff5",textColor:"#ffffff",font:"classic",compact:false,symbol:"✦",subtitle:"",image:"",askGuests:false,askNote:false,customQuestion:""});
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function showSaved(){let list=JSON.parse(localStorage.getItem("invitations")||"[]");$("savedList").innerHTML=list.length?list.map((x,i)=>'<div class="saved"><div><strong>'+esc(x.title||"Sans titre")+'</strong><small>'+esc(x.date||"Sans date")+'</small></div><button class="ghost small" data-load="'+i+'">Ouvrir</button></div>').join(""):"<p style='color:#999'>Aucune création enregistrée.</p>";document.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>{fill(list[+b.dataset.load]);$("modal").classList.add("hidden")})}
$("loadBtn").onclick=()=>{$("modal").classList.remove("hidden");showSaved()};$("closeModal").onclick=()=>$("modal").classList.add("hidden");

let responseAnswer="";let hash=location.hash.match(/^#invite=(.+)$/);let shared=hash&&decode(hash[1]);
if(shared){
 fill(shared);$("shareUrl").value=location.href;document.body.classList.add("guest-mode");
 document.querySelector(".editor").style.display="none";document.querySelector(".preview-area").style.position="static";document.querySelector(".preview-area").style.maxWidth="520px";document.querySelector(".preview-area").style.margin="40px auto";document.querySelector(".share-card").style.display="none";
 $("openBtn").style.display="none";$("loadBtn").style.display="none";$("shareTop").textContent="Créer ma propre invitation";$("shareTop").onclick=()=>{location.href=location.pathname};document.querySelector(".topbar").style.justifyContent="center";
}else render();

const API=(window.INVITATION_API_URL||"").replace(/\/$/,"");
let organizerToken=localStorage.getItem("invitationOrganizerToken")||"";
async function api(path,options={}){if(!API)throw new Error("API non configurée. Configure l’URL du Worker.");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch(API+path,{...options,signal:controller.signal,headers:{"Content-Type":"application/json",...(options.headers||{})}});const raw=await r.text();let j={};try{j=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(j.error||("Erreur serveur ("+r.status+")"));return j}catch(e){if(e.name==="AbortError")throw new Error("Le serveur met trop de temps à répondre.");throw e}finally{clearTimeout(timer)}}
function newToken(){const a=new Uint8Array(24);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function publishInvitation(){read();ensureInviteId();let createdToken=false;if(!organizerToken){organizerToken=newToken();localStorage.setItem("invitationOrganizerToken",organizerToken);createdToken=true}try{await api("/api/invitations",{method:"POST",body:JSON.stringify({token:organizerToken,invitation:data})});$("shareUrl").value=makeUrl();try{await navigator.clipboard?.writeText($("shareUrl").value)}catch{}if(createdToken){$("authToken").value=organizerToken;$("authStatus").textContent="Code organisateur créé. Conserve-le pour retrouver tes invitations sur un autre appareil."}toast("Invitation publiée et lien prêt à partager")}catch(e){toast(e.message||"Publication impossible")}}
$("publishBtn").onclick=publishInvitation;
function openOrganizer(){$("organizerModal").classList.remove("hidden");$("authToken").value=organizerToken;loadDashboard()}
$("organizerBtn").onclick=openOrganizer;$("closeOrganizer").onclick=()=>$("organizerModal").classList.add("hidden");
$("saveTokenBtn").onclick=()=>{const t=$("authToken").value.trim();if(t.length<20){$("authStatus").textContent="Code trop court.";return}organizerToken=t;localStorage.setItem("invitationOrganizerToken",t);$("authStatus").textContent="Code enregistré.";loadDashboard()};
$("newTokenBtn").onclick=()=>{if(organizerToken){$("authToken").value=organizerToken;$("authStatus").textContent="Un code est déjà utilisé. Il est conservé pour éviter de perdre l’accès à tes invitations.";toast("Code actuel conservé");return}organizerToken=newToken();$("authToken").value=organizerToken;$("authStatus").textContent="Nouveau code créé. Enregistre-le puis publie une invitation.";};
$("logoutBtn").onclick=()=>{organizerToken="";localStorage.removeItem("invitationOrganizerToken");$("authToken").value="";$("dashboardList").innerHTML="<p class='hint'>Code effacé de cet appareil.</p>"};
$("refreshDashboard").onclick=loadDashboard;
async function loadDashboard(){const list=$("dashboardList");list.innerHTML="<p class='hint'>Chargement…</p>";if(!organizerToken){list.innerHTML="<p class='hint'>Crée ou saisis ton code organisateur.</p>";return}try{const j=await api("/api/invitations",{headers:{"X-Organizer-Token":organizerToken}});if(!j.invitations.length){list.innerHTML="<p class='hint'>Aucune invitation publiée avec ce code.</p>";return}list.innerHTML=j.invitations.map(inv=>{const yes=inv.responses.filter(r=>r.answer==="yes").length,no=inv.responses.filter(r=>r.answer==="no").length;return '<div class="saved"><div><strong>'+esc(inv.title||"Invitation")+'</strong><small>Présents : '+yes+' · Absents : '+no+' · Réponses : '+inv.responses.length+'</small></div><div><button class="ghost small" data-export="'+esc(inv.inviteId)+'">CSV</button><button class="ghost small" data-delete="'+esc(inv.inviteId)+'">Supprimer</button></div></div>'}).join("");document.querySelectorAll("[data-export]").forEach(b=>b.onclick=()=>exportInvitation(b.dataset.export,j.invitations));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("Supprimer cette invitation et ses réponses ?"))return;try{await api("/api/invitations/"+encodeURIComponent(b.dataset.delete),{method:"DELETE",headers:{"X-Organizer-Token":organizerToken}});toast("Invitation supprimée");loadDashboard()}catch(e){toast(e.message)}})}catch(e){list.innerHTML="<p class='hint'>"+esc(e.message)+"</p>"}}
function exportInvitation(id,invitations){const inv=invitations.find(x=>x.inviteId===id);if(!inv)return;const rows=[["Nom","Réponse","Personnes","Message","Question","Date"]];inv.responses.forEach(r=>rows.push([r.name||"",r.answer==="yes"?"Présent":"Absent",r.count||1,r.note||"",r.custom||"",new Date(r.createdAt).toLocaleString("fr-FR")]));const csv=rows.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=(inv.title||"invitation").replace(/[^a-z0-9à-ÿ]+/gi,"-")+".csv";a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll(".rsvp-buttons button").forEach(b=>b.onclick=()=>{
 if(!data.rsvp)return;responseAnswer=b.dataset.answer;$("responseTitle").textContent=responseAnswer==="yes"?"Je viens":"Je ne peux pas";$("responseModal").classList.remove("hidden");$("guestName").focus();
});
$("closeResponse").onclick=()=>$("responseModal").classList.add("hidden");
function responseText(){let parts=[data.title||"Invitation",responseAnswer==="yes"?"Je viens":"Je ne peux pas","Nom : "+($("guestName").value||"Non indiqué")];if(data.askGuests)parts.push("Personnes : "+$("guestCount").value);if(data.askNote&&$("guestNote").value)parts.push("Message : "+$("guestNote").value);if(data.customQuestion&&$("guestCustom").value)parts.push(data.customQuestion+" : "+$("guestCustom").value);return parts.join("\n")}
$("copyResponse").onclick=async()=>{let t=responseText();try{await navigator.clipboard.writeText(t);toast("Réponse copiée")}catch{toast("Impossible de copier automatiquement")}};
$("sendResponse").onclick=async()=>{let t=responseText();let response={answer:responseAnswer,name:$("guestName").value.trim(),count:data.askGuests?Number($("guestCount").value||1):1,note:data.askNote?$("guestNote").value.trim():"",custom:data.customQuestion?$("guestCustom").value.trim():""};if(API&&data.inviteId){try{await api("/api/invitations/"+encodeURIComponent(data.inviteId)+"/responses",{method:"POST",body:JSON.stringify(response)});toast("Réponse envoyée");$("responseModal").classList.add("hidden");return}catch(e){toast(e.message||"Envoi en ligne impossible")}}if(data.contact&&data.contact.includes("@")){location.href="mailto:"+encodeURIComponent(data.contact.trim())+"?subject="+encodeURIComponent("Réponse à l’invitation — "+(data.title||"Invitation"))+"&body="+encodeURIComponent(t)}else{navigator.clipboard?.writeText(t);toast(data.contact?"Réponse préparée et copiée":"Réponse copiée : partage-la à l’organisateur");$("responseModal").classList.add("hidden")}};
